server:
  port: 9092
  http2:
    enabled: true

graphql:
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank account sample query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
  servlet:
    max-query-depth: 5
    max-query-complexity: 5
#    exception-handlers-enabled: true

spring:
  graphql:
    instrumentation:
      max-query-complexity: 100 # DDOS attack
      max-query-depth: 10 # DDOS attack limit

    graphiql:
      enabled: true
    cors:
      allowed-origins: /**
    schema:
      printer:
        enabled: true

voyager:
  enabled: false